lesson_52/news_project/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from .views import dashboard_view, user_login, SignUpView
from .forms import CustomPasswordChangeForm
from django.views.generic import TemplateView
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', user_login, name='login'),
    # path('login/', views.CustomLoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="accounts:logged_out"),
        name="logout",
    ),
    path(
        "logged-out/",
        TemplateView.as_view(template_name="registration/logged_out.html"),
        name="logged_out",
    ),
    path('signup/', SignUpView.as_view(), name='register'),
    path(
        "register/done/",
        TemplateView.as_view(template_name="accounts/register_done.html"),
        name="register_done",
    ),
    path(
        'password_change/', 
        PasswordChangeView.as_view(
            template_name='registration/password_change_form.html',
            success_url='/accounts/password_change/done/',
            form_class=CustomPasswordChangeForm
        ), 
        name='password_change'
    ),
    
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'
        ),
        name='password_change_done'
    ),
    
    path(
        'password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset_form.html',
            success_url=reverse_lazy('accounts:password_reset_done')
        ),
        name='password_reset'
    ),
    
    path(
        'password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    
    path(
        'password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    
    # path('profile/', dashboard_view, name='user_profile'),
    path('profile/', views.dashboard_view, name='user_profile'),
    # path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('admin-page/', views.admin_page, name='admin_page'),
]

lesson_52/news_project/news_app/urls.py
from django.urls import path
from . import views
from .views import(
  HomePageView, 
  SinglePageView, 
  NewsListView, 
  AboutPageView, 
  ContactPageView, 
  custom_404_view, 
  CategoryDetailView, 
  NewsCreateView, 
  NewsUpdateView, 
  NewsDeleteView
)

app_name = "news"

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('news/', NewsListView.as_view(), name='news_list'),
    # path("search/", views.search_view, name="search"),
    path("search/", views.SearchResultsView.as_view(), name="search"),
    path("news/create/", NewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/edit/", NewsUpdateView.as_view(), name="news_edit"),
    path("news/<int:pk>/delete/", NewsDeleteView.as_view(), name="news_delete"),
    path('news/<slug:slug>/', SinglePageView.as_view(), name='news_detail'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('404/', custom_404_view, name='404'),
]

lesson_52/news_project/news_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("news_app.urls", namespace="news")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
)

handler404 = "news_app.views.custom_404_view"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

lesson_52/news_project/templates/news/about.html
{% extends 'news/base.html' %}
{% load static %}
{% load i18n %}

{% block title %} About - NewsFeed {% endblock %}

{% block content %}
<section id="contentSection">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <div class="left_content">
                <div class="single_page">
                    <h1>{% trans "Biz Haqimizda" %}</h1>
                    <div class="post_commentbox">
                        <a href="#"><i class="fa fa-user"></i>Admin</a>
                        <a href="#"><i class="fa fa-calendar"></i>{% now "F j, Y" %}</a>
                        <a href="#"><i class="fa fa-tags"></i>About Us</a>
                    </div>
                    
                    <div class="single_page_content">
                        <img class="img-center" src="{% static 'images/about_us.jpg' %}" alt="About Us">
                        
                        <h2>{% trans "Bizning Missiyamiz" %}</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                        
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                        
                        <blockquote>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.</blockquote>
                        
                        <h2>{% trans "Bizning Jamoamiz" %}</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua:</p>
                        
                        <ul>
                            <li>Qualified professionals</li>
                            <li>Years of experience</li>
                            <li>Modern technologies</li>
                            <li>Customer satisfaction</li>
                        </ul>
                        
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                    
                    <div class="social_link">
                        <ul class="sociallink_nav">
                            <li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa-brands fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa-brands fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa-brands fa-pinterest"></i></a></li>
                        </ul>
                    </div>
                    
                </div>
            </div>
        </div>
        
        <div class="col-lg-4 col-md-4 col-sm-4">
            <aside class="right_content">
                <div class="single_sidebar">
                    <h2><span>{% trans "Bizning Jamoa" %}</span></h2>
                    <ul class="spost_nav">
                        <li>
                            <div class="media wow fadeInDown"> 
                                <a href="#" class="media-left"> 
                                    <img alt="" src="{% static 'images/rasm_011.jpg' %}"> 
                                </a>
                                <div class="media-body"> 
                                    <a href="#" class="catg_title">John Doe - Bosh Muharrir</a> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="media wow fadeInDown"> 
                                <a href="#" class="media-left"> 
                                    <img alt="" src="{% static 'images/rasm_022.jpg' %}"> 
                                </a>
                                <div class="media-body"> 
                                    <a href="#" class="catg_title">Jane Smith - Jurnalist</a> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="media wow fadeInDown"> 
                                <a href="#" class="media-left"> 
                                    <img alt="" src="{% static 'images/rasm_033.jpg' %}"> 
                                </a>
                                <div class="media-body"> 
                                    <a href="#" class="catg_title">Mike Johnson - Fotograf</a> 
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                
                <div class="single_sidebar">
                    <h2><span>{% trans "Ko'p O'qilgan Yangiliklar" %}</span></h2>
                    <ul class="spost_nav">
                        <li>
                            <div class="media wow fadeInDown"> 
                                <a href="#" class="media-left"> 
                                    <img alt="" src="{% static 'images/post_img1.jpg' %}"> 
                                </a>
                                <div class="media-body"> 
                                    <a href="#" class="catg_title">{% trans "Eng Mashhur Yangilik 1" %}</a> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="media wow fadeInDown"> 
                                <a href="#" class="media-left"> 
                                    <img alt="" src="{% static 'images/post_img2.jpg' %}"> 
                                </a>
                                <div class="media-body"> 
                                    <a href="#" class="catg_title">{% trans "Eng Mashhur Yangilik 2" %}</a> 
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                
                <div class="single_sidebar wow fadeInDown">
                    <h2><span>Reklama</span></h2>
                    <a class="sideAdd" href="#"><img src="{% static 'images/add_img.jpg' %}" alt=""></a>
                </div>
            </aside>
        </div>
    </div>
</section>
{% endblock %}

lesson_52/news_project/templates/news/category_detail.html
{% extends 'news/base.html' %}
{% load static %}
{% load i18n %}

{% block title %} {{ category.get_translate_name }} - NewsFeed {% endblock %}

{% block content %}
<section id="contentSection">
  <div class="row">
    <!-- Asosiy kontent -->
    <div class="col-lg-8 col-md-8 col-sm-8">
      <div class="left_content">
        {% if request.user.is_authenticated and request.user.is_staff %}
            <a href="{% url 'news:news_create' %}" class="btn btn-purple mb-3">{% trans " Yangi Yangilik Qo'shish" %}</a>
        {% elif request.user.is_authenticated and request.user.is_superuser %}
            <a href="{% url 'news:news_create' %}" class="btn btn-purple mb-3">{% trans " Yangi Yangilik Qo'shish" %}</a>
        {% endif %}
        <div class="single_post_content">
          <h2><span>{{ category.get_translate_name }}</span></h2>
          <div class="single_post_content_left">
            <ul class="business_catgnav wow fadeInDown">
              {% for news_item in news_list %}
                {% if forloop.first %}
                  <li>
                    <figure class="bsbig_fig">
                      <a href="{{ news_item.get_absolute_url }}" class="featured_img">
                        <img src="{{ news_item.image.url }}" alt="{{ news_item.title }}">
                        <span class="overlay"></span>
                      </a>
                      <figcaption>
                        <a href="{{ news_item.get_absolute_url }}">{{ news_item.get_translated_title }}</a>
                        <div class="post_meta" style="margin-top: 5px; font-size: 12px; color: #999;">
                          <span>
                            <i class="fa fa-clock-o"></i> {{ news_item.published_at|date:"d.m.Y H:i" }}
                          </span>
                          <span style="margin-left: 10px;">
                            <i class="fa fa-eye"></i> {{ news_item.views }}
                          </span>
                        </div>
                      </figcaption>
                      <p>{{ news_item.get_translated_content|safe|truncatewords:20 }}</p>
                    </figure>
                  </li>
                {% endif %}
              {% empty %}
                <p>{% trans "Bu kategoriyada yangiliklar mavjud emas." %}</p>
              {% endfor %}
            </ul>
          </div>

          <!-- Qolgan yangiliklar -->
          <div class="single_post_content_right">
            <ul class="spost_nav">
              {% for news_item in news_list %}
                {% if forloop.counter > 1 %}
                  <li>
                    <div class="media wow fadeInDown">
                      <a href="{{ news_item.get_absolute_url }}" class="media-left">
                        <img alt="{{ news_item.title }}" src="{{ news_item.image.url }}">
                      </a>
                      <div class="media-body"> 
                        <a href="{{ news_item.get_absolute_url }}" class="catg_title">{{ news_item.get_translated_title }}</a>
                        <div class="post_meta" style="margin-top: 5px; font-size: 12px; color: #999;">
                          <span>
                            <i class="fa fa-clock-o"></i> {{ news_item.published_at|date:"d.m.Y H:i" }}
                          </span>
                          <span style="margin-left: 10px;">
                            <i class="fa fa-eye"></i> {{ news_item.views }}
                          </span>
                        </div>
                      </div>
                    </div>
                  </li>
                {% endif %}
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- O'ng panel -->
    <div class="col-lg-4 col-md-4 col-sm-4">
      <aside class="right_content">
        <div class="single_sidebar">
          <h2><span>{% trans "Ommabop" %}</span></h2>
          <ul class="spost_nav">
            <li>
              <div class="media wow fadeInDown">
                <a href="#" class="media-left"><img src="{% static 'images/post_img1.jpg' %}" alt=""></a>
                <div class="media-body">
                  <a href="#" class="catg_title">{% trans "Mashhur yangilik namunasi" %}</a>
                </div>
              </div>
            </li>
          </ul>
        </div>

        <div class="single_sidebar">
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#category" aria-controls="home" role="tab" data-toggle="tab">{% trans "Kategoriya" %}</a></li>
            <li role="presentation"><a href="#video" aria-controls="profile" role="tab" data-toggle="tab">{% trans "Video" %}</a></li>
            <li role="presentation"><a href="#comments" aria-controls="messages" role="tab" data-toggle="tab">{% trans "Izohlar" %}</a></li>
          </ul>
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="category">
              <ul>
                {% for cat in categories %}
                  <li class="cat-item"><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
                {% endfor %}
              </ul>
            </div>
            <div role="tabpanel" class="tab-pane" id="video">
              <div class="vide_area">
                <iframe width="100%" height="250" src="http://www.youtube.com/embed/h5QWbURNEpA" frameborder="0" allowfullscreen></iframe>
              </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="comments">
              <p>{% trans "Izohlar bo‘limi tez orada qo‘shiladi." %}</p>
            </div>
          </div>
        </div>

        <div class="single_sidebar wow fadeInDown">
          <h2><span>Sponsor</span></h2>
          <a class="sideAdd" href="#"><img src="{% static 'images/add_img.jpg' %}" alt="Advertisement"></a>
        </div>

        <div class="single_sidebar wow fadeInDown">
          <h2><span>{% trans "Barcha yangiliklar" %}</span></h2>
          <select class="catgArchive">
            <option>{% trans "Categoriyani tanlang" %}</option>
            {% for cat in categories %}
              <option>{{ cat.get_translate_name }}</option>
            {% endfor %}
          </select>
        </div>
      </aside>
    </div>
  </div>
</section>
{% endblock content %}

lesson_52/news_project/templates/news/contact.html
{% extends 'news/base.html' %}
{% load static %}
{% load i18n %}

{% block title %} Biz bilan aloqa - NewsFeed {% endblock %}
{% block content %}
  <section id="contentSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="left_content">
          <div class="contact_area">
            <h2>{% trans "Biz bilan aloqa" %}</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labolore magna aliqua. Ut enim ad minim veniam. Lorem ipsum dosectetur adipisicing elit, sed do.Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <!-- SUCCESS yoki ERROR xabarlar shu yerda chiqadi -->
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            <form action="#" class="contact_form" method="post"> {% csrf_token %}
              <input class="form-control" type="text" placeholder="Name*" name="name">
              <input class="form-control" type="email" placeholder="Email*" name="email">
              <textarea class="form-control" cols="30" rows="10" placeholder="Message*" name="message"></textarea>
              <input type="submit" value="Xabar jo'natish">
            </form>            
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <aside class="right_content">
          <div class="single_sidebar">
            <h2><span>{% trans "Ommabop" %}</span></h2>
            <ul class="spost_nav">
              {% for item in popular_news %}
              <li>
                <div class="media wow fadeInDown"> <a href="{% url 'news:news_detail' item.slug %}" class="media-left"> <img alt="" src="{{ item.image.url }}"> </a>
                  <div class="media-body"> <a href="{% url 'news:news_detail' item.slug %}" class="catg_title">{{ item.get_translated_title }}</a> </div>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
    </div>
  </section>
{% endblock content %}  

lesson_52/news_project/templates/news/news_by_category.html
{% extends 'news/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}Category: {{ current_category }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Main content -->
        <div class="col-md-8">
            <h2>{% blocktrans %}Yangiliklar: {{ current_category|title }}{% endblocktrans %}</h2>
            {% if news_list %}
                {% for news in news_list %}
                    <div class="news_item">
                        <h3><a href="{{ news.get_absolute_url }}">{{ news.get_translated_title }}</a></h3>
                        <p>{{ news.get_translated_content|safe|truncatewords:30 }}</p>
                        <small>{{ news.published_at|date:"d M Y" }}</small>
                        <hr>
                    </div>
                {% endfor %}
            {% else %}
                <p>{% trans "Bu kategoriya bo‘yicha yangiliklar topilmadi." %}</p>
            {% endif %}

            <!-- Pagination (agar ListView paginate_by ishlatilgan bo‘lsa) -->
            {% if is_paginated %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                        {% endif %}
                        {% for num in paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="active"><a href="#">{{ num }}</a></li>
                            {% else %}
                                <li><a href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>

        <!-- Sidebar -->
        <div class="col-md-4">
            <div class="single_sidebar">
                <h2><span>{% trans "Kategoriyalar" %}</span></h2>
                <ul>
                    {% for cat in categories %}
                        <li class="cat-item">
                            <a href="{{ cat.get_absolute_url }}">{{ cat.get_translate_name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="single_sidebar">
                <h2><span>{% trans "Eng so‘nggi yangiliklar" %}</span></h2>
                <ul>
                    {% for news in latest_news %}
                        <li><a href="{{ news.get_absolute_url }}">{{ news.get_transated_title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lesson_52/news_project/templates/news/news_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/news_app.css' %}">
    <title>News List</title>
</head>
<body>
    <h1>News List</h1>

    <div class="news-container">
        {% for item in news %}
            <a href="{{ item.get_absolute_url }}" class="news-card">
                {% if item.image %}
                    <img src="{{ item.image.url }}" alt="{{ item.title }}">
                {% endif %}
                <div class="news-content">
                    <span class="category">{{ item.category.name }}</span>
                    <h3>{{ item.title|truncatewords:10 }}</h3>
                    <p>{{ item.content|truncatewords:20 }}</p>
                </div>
            </a>
        {% endfor %}
    </div>
</body>
</html>

lesson_52/news_project/templates/news/search_results.html
{% extends "news/base.html" %}

{% load static %}
{% load i18n %}

{% block content %}
<div class="container-fluid my-5">

    <!-- 🔍 Qidiruv formasi -->
    <div class="row mb-4">
        <div class="col-md-8 col-md-offset-2">
            <form method="get" action="{% url 'news:search' %}" class="input-group">
                <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="{% trans 'Qidiruv...' %}">
                <span class="input-group-btn">
                    <button class="btn btn-primary search-btn" type="submit">{% trans "Qidirish" %}</button>
                </span>
            </form>

        </div>
    </div>

    <!-- 📌 Qidiruv natijalari sarlavhasi -->
    <h3 class="text-center mb-4">
        {% if query %}
            {% blocktrans with search=query %}
                Qidiruv natijalari: "{{ search }}"
            {% endblocktrans %}
        {% else %}
            {% blocktrans %}
                Qidiruv natijalari
            {% endblocktrans %}
        {% endif %}
    </h3>

    {% if results %}
        <div class="row">
            {% for item in results %}
                <div class="col-md-6 mb-4">
                    <div class="panel panel-default">
                        
                        <!-- 🖼 Yangilik rasmi -->
                        {% if item.image %}
                            <div style="height: 300px; overflow: hidden;">
                                <img src="{{ item.image.url }}" 
                                    alt="{{ item.title }}" 
                                    class="img-responsive" 
                                    style="width: 100%; height: 100%; object-fit: cover;">
                            </div>
                        {% endif %}

                        <!-- 📄 Kontent -->
                        <div class="panel-body">
                            <h4>
                                <a href="{{ item.get_absolute_url }}" class="text-decoration-none">
                                    {{ item.title }}
                                </a>
                            </h4>
                            <p class="text-muted">{{ item.get_translated_content|truncatechars:120 }}</p>
                        </div>

                        <!-- 📅 Sana, 👤 Muallif va 🏷 Kategoriya -->
                        <div class="panel-footer small text-muted">
                            <span><i class="fa fa-user"></i> {{ item.author }}</span> | 
                            <span><i class="fa fa-calendar"></i> {{ item.published_at|date:"d M Y" }}</span> | 
                            <span><i class="fa fa-tag"></i> {{ item.category.get_translate_name }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- 📄 Pagination -->
        {% if results.has_other_pages %}
        <nav aria-label="Page navigation" class="text-center">
            <ul class="pagination">
                {% if results.has_previous %}
                <!-- <li><a href="?q={{ query }}&page={{ results.previous_page_number }}">« Oldingi</a></li> -->
                <li><a href="?{{ querystring }}&page={{ results.previous_page_number }}">« {% trans "Oldingi" %}</a></li>
                {% endif %}

                {% for num in results.paginator.page_range %}
                    {% if results.number == num %}
                        <li class="active"><span>{{ num }}</span></li>
                    {% elif num > results.number|add:-2 and num < results.number|add:2 %}
                        <!-- <li><a href="?q={{ query }}&page={{ num }}">{{ num }}</a></li> -->
                        <li><a href="?{{ querystring }}&page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if results.has_next %}
                <!-- <li><a href="?q={{ query }}&page={{ results.next_page_number }}">Keyingi »</a></li> -->
                <li><a href="?{{ querystring }}&page={{ results.next_page_number }}">{% trans "Keyingi" %} »</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}

    {% else %}
        <div class="empty-state text-center py-5 px-3">
            <div class="empty-state-icon mb-4">
                <i class="fa-solid fa-search fs-1 icon-search"></i>
            </div>
            <h4 class="fw-semibold text-dark mb-2">{% trans "Hech narsa topilmadi" %}</h4>
            <p class="text-muted mb-0">
                {% trans "Qidiruv natijasi bo'yicha ma'lumot mavjud emas." %}<br>
                {% trans "Iltimos, boshqa kalit so'zlardan foydalanib ko'ring." %}
            </p>
        </div>
    {% endif %}

</div>
{% endblock %}